CREATE TABLE FIRMA.developer
  (
    d_Id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    f_Id NUMBER,
    pId NUMBER,
    yazilimci_adi VARCHAR2( 50 ) NOT NULL,
    
       CONSTRAINT fk_developer_firma FOREIGN KEY( f_Id)
      REFERENCES FIRMA.FIRMA( F_ID )
      ON DELETE CASCADE,
      CONSTRAINT fk_developer_proje 
      FOREIGN KEY( pId )
      REFERENCES FIRMA.PROJE(p_Id)
      ON DELETE SET NULL
    
  );