CREATE TABLE FIRMA.firma
  (
    f_Id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    firma_adi VARCHAR2( 50 ) NOT NULL,
    
     firma_sahibi VARCHAR2( 50 ) NOT NULL
 
        
  );
