CREATE TABLE FIRMA.proje
  (
    p_Id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 5 PRIMARY KEY,
    f_Id NUMBER,
    proje_adi VARCHAR2( 50 ) NOT NULL,
     proje_sure VARCHAR2( 50 ) NOT NULL,
     proje_butce VARCHAR2( 50 ) NOT NULL,
      proje_eleman VARCHAR2( 10 ) NOT NULL,
       CONSTRAINT fk_proje_firma FOREIGN KEY( f_Id)
      REFERENCES FIRMA.FIRMA( F_ID )
      ON DELETE CASCADE);
      